### PR TITLE
Improve discussions' threads rendering, fixes #37

### LINKED ISSUE #37: Improve discussions' threads rendering
As a visitor, I want a better rendering of avatars and permalinks in order to be consistent across the website.

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by davidbgk** [comment]
Do not miss the gouvfr related one: https://github.com/etalab/udata-gouvfr/pull/15

**Comment by davidbgk** [comment]
## On datasets

capture d ecran 2015-06-01 a 11 42 02

## On reuses

capture d ecran 2015-06-01 a 11 43 42

**Comment by noirbizarre** [comment]
Great.

Do we only put a link button or do we use a share button ?

**Comment by davidbgk** [comment]
I think that a link button is enough, I'm not sure that it's pertinent to share a discussion (vs. a dataset or a reuse) but I may be wrong.

**Comment by noirbizarre** [comment]
Good to me.

r+

**Pull request merged**
