### PR TITLE
Fix js translatable string extraction

### PR DESCRIPTION
**Pull request by noirbizarre**
This PR fixes JS string extraction, move the function from udata commands to an invoke task (and cleanup invoke tasks)

### CODE REVIEW

**Comment by davidbgk** [comment]
Flake8 and JSHint, yay!

**Comment by noirbizarre** [comment]
Yes, we will need to fix lints soon, there are a lot of them ! :open_mouth:

**Comment by davidbgk** [comment]
I can take care of that during a train commute ;)

**Comment by noirbizarre** [comment]
Good :)
After that, maybe we need to integrate the QA check into the Travis build.
I don't know if it's a little bit violent...

**Comment by davidbgk** [comment]
+1 for adding it to the Travis build, or maybe a pre-commit hook?

r+

**Pull request merged**
