### PR TITLE
Splitting a translation to avoid newlines

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by noirbizarre** [comment]
Need to update the translations files, by either removing the references or updating them:
https://github.com/etalab/udata/blob/master/js/locales/udata.en.json#L59
https://github.com/etalab/udata/blob/master/js/locales/udata.es.json#L59
https://github.com/etalab/udata/blob/master/js/locales/udata.fr.json#L59

**Comment by noirbizarre** [comment]
But R+ ;)

**Comment by davidbgk** [comment]
@noirbizarre isn't it safer to do that via transifex?

**Comment by noirbizarre** [comment]
Yes, but right now the extraction script only extract :)
So we will have a dead key. But maybe the right solution is a check script

**Pull request merged**
