### PR TITLE
Add a FAQ module, fix #28

### LINKED ISSUE #28: Add a FAQ module
As a visitor I want to get basic information tailored for my profile (newcomer, producer, developer or jurist) in order to use the website appropriately.

### PR DESCRIPTION
**Pull request by davidbgk**
As a visitor I want to get basic information tailored for my profile
(newcomer, producer, developer or jurist) in order to use the website
appropriately.

### CODE REVIEW

**Comment by davidbgk** [comment]
## In the main menu (not translated yet)

capture d ecran 2015-05-22 a 16 49 55

## In the footer

capture d ecran 2015-05-22 a 16 50 06

## Home page of the FAQ

capture d ecran 2015-05-22 a 16 50 13

## For citizens  

capture d ecran 2015-05-22 a 16 50 25

## For producers 

capture d ecran 2015-05-22 a 16 51 13

## For developers

capture d ecran 2015-05-22 a 16 50 48

## For jurists

capture d ecran 2015-05-22 a 16 51 01

**Comment by noirbizarre** [comment]
I think templates and tests are missings.

**Comment by davidbgk** [comment]
@noirbizarre you probably missed the udata-gouvfr related PR https://github.com/etalab/udata-gouvfr/pull/14 ;)

What do we want to test?

**Comment by davidbgk** [comment]
That PR is now useless given that I merged changes directly in https://github.com/etalab/udata-gouvfr/pull/14

**Pull request closed without merging**
